2014

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,6 +29,7 @@ jobs:
         id: build_image
         run: |
           docker build -t flask-app:latest . || { echo 'Docker image build failed'; exit 1; }
+          echo "Docker image built successfully."
 
       - name: Deploy to EC2
         if: steps.build_image.outcome == 'success'
@@ -39,7 +40,12 @@ jobs:
         run: |
           printf "%s" "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
           chmod 600 private_key.pem
+          echo "Connecting to EC2 instance..."
           ssh -o StrictHostKeyChecking=no -i private_key.pem ${USERNAME}@${HOST} "
-              docker save flask-app:latest | docker load || { echo 'Docker load failed'; exit 1; } &&
-              docker-compose up -d
+              echo 'Saving Docker image...' &&
+              docker save flask-app:latest > flask-app.tar || { echo 'Docker save failed'; exit 1; } &&
+              echo 'Loading Docker image...' &&
+              cat flask-app.tar | docker load || { echo 'Docker load failed'; exit 1; } &&
+              echo 'Starting Docker containers...' &&
+              docker-compose up -d || { echo 'Docker compose up failed'; exit 1; }
           "
